// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cummax_by_group_cpp
IntegerVector cummax_by_group_cpp(IntegerVector x, IntegerVector group);
RcppExport SEXP _DIDmultiplegtDYN_cummax_by_group_cpp(SEXP xSEXP, SEXP groupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    rcpp_result_gen = Rcpp::wrap(cummax_by_group_cpp(x, group));
    return rcpp_result_gen;
END_RCPP
}
// compute_var_covar_matrix_cpp
NumericMatrix compute_var_covar_matrix_cpp(NumericMatrix U_Gg_vars, IntegerVector first_obs, int l_XX, double G_XX);
RcppExport SEXP _DIDmultiplegtDYN_compute_var_covar_matrix_cpp(SEXP U_Gg_varsSEXP, SEXP first_obsSEXP, SEXP l_XXSEXP, SEXP G_XXSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type U_Gg_vars(U_Gg_varsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type first_obs(first_obsSEXP);
    Rcpp::traits::input_parameter< int >::type l_XX(l_XXSEXP);
    Rcpp::traits::input_parameter< double >::type G_XX(G_XXSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_var_covar_matrix_cpp(U_Gg_vars, first_obs, l_XX, G_XX));
    return rcpp_result_gen;
END_RCPP
}
// compute_U_Gg_global_cpp
NumericVector compute_U_Gg_global_cpp(NumericVector U_Gg_plus, NumericVector U_Gg_minus, double N1_weight, double N0_weight);
RcppExport SEXP _DIDmultiplegtDYN_compute_U_Gg_global_cpp(SEXP U_Gg_plusSEXP, SEXP U_Gg_minusSEXP, SEXP N1_weightSEXP, SEXP N0_weightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type U_Gg_plus(U_Gg_plusSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type U_Gg_minus(U_Gg_minusSEXP);
    Rcpp::traits::input_parameter< double >::type N1_weight(N1_weightSEXP);
    Rcpp::traits::input_parameter< double >::type N0_weight(N0_weightSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_U_Gg_global_cpp(U_Gg_plus, U_Gg_minus, N1_weight, N0_weight));
    return rcpp_result_gen;
END_RCPP
}
// compute_clustered_variance_cpp
List compute_clustered_variance_cpp(NumericVector U_Gg_var, IntegerVector first_obs_gp, IntegerVector first_obs_clust, IntegerVector cluster, double G_XX);
RcppExport SEXP _DIDmultiplegtDYN_compute_clustered_variance_cpp(SEXP U_Gg_varSEXP, SEXP first_obs_gpSEXP, SEXP first_obs_clustSEXP, SEXP clusterSEXP, SEXP G_XXSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type U_Gg_var(U_Gg_varSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type first_obs_gp(first_obs_gpSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type first_obs_clust(first_obs_clustSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cluster(clusterSEXP);
    Rcpp::traits::input_parameter< double >::type G_XX(G_XXSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_clustered_variance_cpp(U_Gg_var, first_obs_gp, first_obs_clust, cluster, G_XX));
    return rcpp_result_gen;
END_RCPP
}
// propagate_treatment_change_cpp
NumericVector propagate_treatment_change_cpp(NumericVector ever_change, IntegerVector group, IntegerVector time, int T_max);
RcppExport SEXP _DIDmultiplegtDYN_propagate_treatment_change_cpp(SEXP ever_changeSEXP, SEXP groupSEXP, SEXP timeSEXP, SEXP T_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type ever_change(ever_changeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< int >::type T_max(T_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(propagate_treatment_change_cpp(ever_change, group, time, T_max));
    return rcpp_result_gen;
END_RCPP
}
// initialize_effect_columns_cpp
NumericMatrix initialize_effect_columns_cpp(int nrow, int l_XX, bool include_placebo);
RcppExport SEXP _DIDmultiplegtDYN_initialize_effect_columns_cpp(SEXP nrowSEXP, SEXP l_XXSEXP, SEXP include_placeboSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type l_XX(l_XXSEXP);
    Rcpp::traits::input_parameter< bool >::type include_placebo(include_placeboSEXP);
    rcpp_result_gen = Rcpp::wrap(initialize_effect_columns_cpp(nrow, l_XX, include_placebo));
    return rcpp_result_gen;
END_RCPP
}
// compute_weighted_sum_cpp
double compute_weighted_sum_cpp(NumericVector x, IntegerVector mask);
RcppExport SEXP _DIDmultiplegtDYN_compute_weighted_sum_cpp(SEXP xSEXP, SEXP maskSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type mask(maskSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_weighted_sum_cpp(x, mask));
    return rcpp_result_gen;
END_RCPP
}
// compute_delta_D_g_cpp
NumericVector compute_delta_D_g_cpp(NumericMatrix delta_plus, NumericMatrix delta_minus, IntegerVector switchers_tag, int l_XX);
RcppExport SEXP _DIDmultiplegtDYN_compute_delta_D_g_cpp(SEXP delta_plusSEXP, SEXP delta_minusSEXP, SEXP switchers_tagSEXP, SEXP l_XXSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type delta_plus(delta_plusSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type delta_minus(delta_minusSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type switchers_tag(switchers_tagSEXP);
    Rcpp::traits::input_parameter< int >::type l_XX(l_XXSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_delta_D_g_cpp(delta_plus, delta_minus, switchers_tag, l_XX));
    return rcpp_result_gen;
END_RCPP
}
// compute_full_vcov_cpp
List compute_full_vcov_cpp(NumericMatrix U_Gg_vars_effects, NumericMatrix U_Gg_vars_placebos, IntegerVector first_obs, NumericVector se_effects, NumericVector se_placebos, double G_XX);
RcppExport SEXP _DIDmultiplegtDYN_compute_full_vcov_cpp(SEXP U_Gg_vars_effectsSEXP, SEXP U_Gg_vars_placebosSEXP, SEXP first_obsSEXP, SEXP se_effectsSEXP, SEXP se_placebosSEXP, SEXP G_XXSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type U_Gg_vars_effects(U_Gg_vars_effectsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type U_Gg_vars_placebos(U_Gg_vars_placebosSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type first_obs(first_obsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type se_effects(se_effectsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type se_placebos(se_placebosSEXP);
    Rcpp::traits::input_parameter< double >::type G_XX(G_XXSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_full_vcov_cpp(U_Gg_vars_effects, U_Gg_vars_placebos, first_obs, se_effects, se_placebos, G_XX));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DIDmultiplegtDYN_cummax_by_group_cpp", (DL_FUNC) &_DIDmultiplegtDYN_cummax_by_group_cpp, 2},
    {"_DIDmultiplegtDYN_compute_var_covar_matrix_cpp", (DL_FUNC) &_DIDmultiplegtDYN_compute_var_covar_matrix_cpp, 4},
    {"_DIDmultiplegtDYN_compute_U_Gg_global_cpp", (DL_FUNC) &_DIDmultiplegtDYN_compute_U_Gg_global_cpp, 4},
    {"_DIDmultiplegtDYN_compute_clustered_variance_cpp", (DL_FUNC) &_DIDmultiplegtDYN_compute_clustered_variance_cpp, 5},
    {"_DIDmultiplegtDYN_propagate_treatment_change_cpp", (DL_FUNC) &_DIDmultiplegtDYN_propagate_treatment_change_cpp, 4},
    {"_DIDmultiplegtDYN_initialize_effect_columns_cpp", (DL_FUNC) &_DIDmultiplegtDYN_initialize_effect_columns_cpp, 3},
    {"_DIDmultiplegtDYN_compute_weighted_sum_cpp", (DL_FUNC) &_DIDmultiplegtDYN_compute_weighted_sum_cpp, 2},
    {"_DIDmultiplegtDYN_compute_delta_D_g_cpp", (DL_FUNC) &_DIDmultiplegtDYN_compute_delta_D_g_cpp, 4},
    {"_DIDmultiplegtDYN_compute_full_vcov_cpp", (DL_FUNC) &_DIDmultiplegtDYN_compute_full_vcov_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_DIDmultiplegtDYN(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
