# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cummax_by_group_cpp <- function(x, group) {
    .Call(`_DIDmultiplegtDYN_cummax_by_group_cpp`, x, group)
}

compute_var_covar_matrix_cpp <- function(U_Gg_vars, first_obs, l_XX, G_XX) {
    .Call(`_DIDmultiplegtDYN_compute_var_covar_matrix_cpp`, U_Gg_vars, first_obs, l_XX, G_XX)
}

compute_U_Gg_global_cpp <- function(U_Gg_plus, U_Gg_minus, N1_weight, N0_weight) {
    .Call(`_DIDmultiplegtDYN_compute_U_Gg_global_cpp`, U_Gg_plus, U_Gg_minus, N1_weight, N0_weight)
}

compute_clustered_variance_cpp <- function(U_Gg_var, first_obs_gp, first_obs_clust, cluster, G_XX) {
    .Call(`_DIDmultiplegtDYN_compute_clustered_variance_cpp`, U_Gg_var, first_obs_gp, first_obs_clust, cluster, G_XX)
}

propagate_treatment_change_cpp <- function(ever_change, group, time, T_max) {
    .Call(`_DIDmultiplegtDYN_propagate_treatment_change_cpp`, ever_change, group, time, T_max)
}

initialize_effect_columns_cpp <- function(nrow, l_XX, include_placebo) {
    .Call(`_DIDmultiplegtDYN_initialize_effect_columns_cpp`, nrow, l_XX, include_placebo)
}

compute_weighted_sum_cpp <- function(x, mask) {
    .Call(`_DIDmultiplegtDYN_compute_weighted_sum_cpp`, x, mask)
}

compute_delta_D_g_cpp <- function(delta_plus, delta_minus, switchers_tag, l_XX) {
    .Call(`_DIDmultiplegtDYN_compute_delta_D_g_cpp`, delta_plus, delta_minus, switchers_tag, l_XX)
}

compute_full_vcov_cpp <- function(U_Gg_vars_effects, U_Gg_vars_placebos, first_obs, se_effects, se_placebos, G_XX) {
    .Call(`_DIDmultiplegtDYN_compute_full_vcov_cpp`, U_Gg_vars_effects, U_Gg_vars_placebos, first_obs, se_effects, se_placebos, G_XX)
}

